### PR TITLE
update orthography profile

### PR DESCRIPTION
**Pull request by MacyL**
update the orthography profile

### CODE REVIEW

**Comment by LinguList** [comment]
What are the medials in this one?

**Comment by MacyL** [comment]
`cldfbench lexitools.seallable lexibank_chenhmongmien.py --medials=l,z,ɹ,r,ʐ,ʐʷ,w,j,ɥ,ɭ,lʲ,ʁ,lʷ,c`

**Comment by LinguList** [comment]
Okay, please give me the result without "c", as the "c" is never a medial...

**Comment by MacyL** [comment]
ok, I updated the `wj` to `ɥ` and pushed again.

**Comment by MacyL** [comment]
oh sorry, I didn't see the 'c' comment. The test result is : 
|   Number | Segments   | Structure   |   Examples |
|---------:|:-----------|:------------|-----------:|
|        1 | ȵ c ɯ ²²   | i ? ? t     |          1 |

should I add `ȵc` to `ⁿc` ?

**Comment by LinguList** [comment]
Wait, what did you update?

source: wj
target wj/ɥ

or something else?

**Comment by LinguList** [comment]
sure, c is palatal, ȵ as well, c is a stop, ȵ is a nasal, so this is a
pre-nasalized palatal stop.

**Comment by MacyL** [comment]
> Wait, what did you update? source: wj target wj/ɥ or something else?

Oh I misunderstood you mean change the `wj` to `ɥ` instead of `wj/ɥ`.

**Comment by LinguList** [comment]
No, I mean change wj to wj/ɥ

but you said otherwise ;)

**Comment by MacyL** [comment]
I fixed the issue now :) Should I merge it?

**Comment by LinguList** [comment]
yes, please :)

**Pull request merged**
