### PR TITLE
Regenerate CLDF

### PR DESCRIPTION
**Pull request by chrzyki**
@MacyL I've regenerate the CLDF. Can you check the changes in `forms` and languages?

### CODE REVIEW

**Comment by xrotwang** [comment]
I'd suggest a final buildbot run before release - and maybe also add this as step for whatever release instructions we have (or should have) for lexibank.

**Comment by chrzyki** [comment]
@xrotwang Yes, will do the buildbot run after the merge.

**Comment by MacyL** [comment]
checking now, might take about 20 mins :) I will run it with my workflow and the cldfbench commandline

**Comment by chrzyki** [comment]
Thanks. I'll see how buildbot goes and release in a bit as 2.1.0 if that's okay for you?

**Pull request merged**
