### PR TITLE
Change profile for nasalis sonans

### PR DESCRIPTION
**Pull request by tresoldi**
Incorporating @MacyL changes addressing https://github.com/lexibank/chenhmongmien/issues/15

### CODE REVIEW

**Comment by LinguList** [comment]
@macyl, have you checked to make sure that these are the only instances?
I assume it is also possible that we have cases like "fn⁵" or similar,
not only "fŋ⁵", you see? Also, see if there are single nasals, like "ŋ⁵"
o similar. These should be represented as "ŋ */ə ŋ ⁵", and "n⁵" as "n
*/ə n ⁵", you see?

**Comment by MacyL** [comment]
@LinguList, I am checking if there are cases like : "ŋ⁵". 
Meanwhile, I found that some cases that I need help with: 
1. unknown tones :  I am checking the book if the author mentioned these cases. But I would like to know if we have any specific character to mark an unknown tone in the word (e.g. "xut" -- > "xut*/ᵀ")  
2. the template tends to align words like " w j ɛ n ⁵³ "  to  "m n c t", but it should be "i m n t". Can I add a structure column in the orthography profile and manually give the templates to these cases?

**Comment by LinguList** [comment]
Okay, unknown tones, I usually mark them with ⁰, since most of the time
they are zero-tones, like in Mandarin.

**Comment by LinguList** [comment]
> the template tends to align words like " w j ɛ n ⁵³ " to "m n c t", but it should be "i m n t". Can I add a structure column in the orthography profile and manually give the templates to these cases?

This was my idea in the past, but it is problematic, as it is a lot of work. I prefer to change the code I use for making the template. Can you file an isssue with sinopy on this matter?

**Comment by LinguList** [comment]
Okay, in fact, we can also handle this from within the orthography
profile alone.

The wjen-case is pretty problematic, since "wj" is usually one sound
"ɥ". Now, with the other example, "w u/w a", this is originally "wua",
so we have again a problem, as our modification makes this like "wwa",
but this is not true, of course, there is no long "w:", but it means
simply, in our phonological notation, that the initial is "w", and the
medial as well, since in these syllables, if the initial is "w" or if it
is "ɥ", the medial is usually the same as the initial. In fact, one can
say that there is NO initial in this word. So if we stick to "w u/w a" =
"w w a", which looks strange, we could write "wjen" as "wj/ɥ wj/ɥ e n".
But this is somehow all not very nice.

Can you specify exactly how many cases we find there?

**Comment by MacyL** [comment]
6 cases : 
ʐ a ³² + w u/w a ⁵³
w j ɛ n ⁵³
w u/w a ⁴²
w j e ²³¹
w u/w a ³² + p ʐ a ŋ ³⁵
w j a ŋ ³¹

wrong alignment, 3 cases:
ⁿp u/ʐʷ ¹³   ----> "i t"
ⁿp u/lʷ ¹³ ----> "i t"
ts i ⁵⁵ + t l u/w a ³¹

might be able to fix once the superscript 0 is added, 1 case:
g uː ŋ + d oː m ³⁵

**Comment by LinguList** [comment]
Okay, these are also issues in the profile and the like. Will look at
those tomorrow.

**Pull request closed without merging**
