### PR TITLE
explicit closes() are not need in context block

### PR DESCRIPTION
**Pull request by SimonGreenhill**
(just spotted this while looking at the code)

### CODE REVIEW

**Comment by xrotwang** [comment]
I think this is a good candidate dataset for a code review, since it could be simplified using tools from `cldfbench`, e.g. replacing `self.dir.joinpath('raw')` with `self.raw_dir` and generally making use of the methods of https://github.com/cldf/cldfbench/blob/9a4ed2dd637f6f80f8e3fe8e789b9905aef166b6/src/cldfbench/datadir.py#L30

**Comment by xrotwang** [comment]
In fact, I think, proper usage of `cldfbench` tools should push this dataset's python module to <100 lines of code - which may translate to one "screen-full" on big enough screens :)

**Comment by LinguList** [comment]
@MacyL, as you were also involved in this, and also wanted to learn more lexibank usage, please have a close look on this code review here, as it may be important.

**Comment by LinguList** [comment]
In fact, I'd ask @tresoldi, @Bibiko, @chrzyki also to have a close look here (apart from @SimonGreenhill and @xrotwang already looking into it): we can use this as an example for major aspects of coding, also because it makes active use of orthoprofiles.

BTW: we may in fact make common code reviews for all datasets that are maximally different, specifically based on their usage of adding values:

1. kitchensemitic should not add any forms, as it is too messy
2. chenhmongmien is tinkering with clean_form, which can be handled via dataset-attributes now
3. beidazihui is using `add_form_with_segments`, so a clear-cut case for pre-segmented data

Maybe we find a third nice usecase, maybe IDS or ABVD, we should also have an example of `models.lexeme` being modified.

**Comment by LinguList** [comment]
A, and `bodtkhobwa` is useful to look at as it illustrates partial cognates.

**Pull request merged**
